# Generated by Django 5.0.4 on 2024-04-22 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('img', models.ImageField(blank=True, upload_to='media/images', verbose_name='Фото')),
                ('anons', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('tags', models.TextField(default='', verbose_name='Теги темы')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('types', models.CharField(max_length=100, verbose_name='Типы')),
                ('pricing', models.CharField(max_length=100, verbose_name='Цена')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('isopub', models.BooleanField(default=True, verbose_name='Выложено')),
            ],
        ),
    ]
